#! /bin/sh

######################################################################
# FLACUT
# ------
#
# Automated system for cutting up and tagging ".flac" files using the 
# associated ".cue" files
#
# Autor: Alberto Alcolea
#        http://albertoalcolea.com
######################################################################


usage() {
    echo "Usage: $1 [OPTIONS]  FLAC_FILE CUE_FILE"
    echo
    echo "Options:"
    echo "  -r, --rename    rename format (like lltag format)"
    echo "  -d, --delete     delete the origin files (.flac and .cue) after cutting"
    echo "  -h, --help      show this help"
    echo
    echo "  FLAC_FILE (file .flac). CUE_FILE (file .cue)"
    echo "  Default format: \"%n - %t\". See lltag help for more information."
    echo
    echo "Examples:"
    echo "  flacut bigflac.flac cueinfo.cue"
    echo
    echo "  flacut -r \"%n - %t\" bigflac.flac cueinfo.cue"
    echo "      Will rename the multiple flac files with number and title of track."
}


need_dependency() {
    echo "You need to install '$1' to run this application"
    exit 2
}


# Check exist of the required dependencies
check_dependencies() {
    # cuetools
    which cuebreakpoints > /dev/null
    if [ ! `echo $?` = 0 ] ; then
        need_dependency "cuetools"
    fi

    which cuetag > /dev/null
    if [ ! `echo $?` = 0 ] ; then
        need_dependency "cuetools"
    fi

    # lltag
    which lltag > /dev/null
    if [ ! `echo $?` = 0 ] ; then
        need_dependency "lltag"
    fi
}



#########
# MAIN
#########

# Options
RENAME="%n - %t"
DELETE=0

# Collect the arguments that the application has been called
for i in $*
do
	case $i in
        -r|--rename) RENAME=$2; shift; shift;;
        -d|--delete) DELETE=1; shift;;
        -h|--help) usage $0; exit 0; shift;;
        *) ;;
	esac
done

if [ $# != 2 ] ; then
    usage $0
    exit 1
else
    FFLAC="$1"
    FCUE="$2"
fi


check_dependencies


# Cut the big flac file into multiple tracks, according to the index of the cue file
echo
echo "Dividing flac file into multiple tracks"
echo
cuebreakpoints "$FCUE" | shnsplit -o flac "$FFLAC"


# Apply the tags to the generated files
echo
echo "Applying tags to tracks"
echo
cuetag "$FCUE" split-track*.flac


# Rename the files according to the tags
echo
echo "Renaming tracks according to the associated tags"
echo
lltag --yes --no-tagging --rename '%n - %t' `ls split-track*.flac`


# if necessary, delete the origin files
if [ $DELETE = 1 ]; then
    rm FFLAC FCUE
fi

exit 0
